name: Build vm images

on:
 workflow_call:
    secrets:
      ssh-key:
        description: 'ssh key for checking out source code'
        required: true
      rt-user:
        description: 'user account for artifactory'
        required: true
      rt-api-key:
        description: 'api-key for artifactory'
        required: true
      rt-url:
        description: 'artifactory url'
        required: true

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for using local actions
        uses: actions/checkout@v2
      - name: Download manifest
        uses: actions/download-artifact@v3
        with:
          name: workspace
        
      - name: Dump build info
        run: |
          echo "Using manifest:"
          echo -e '${{ steps.checkout.outputs.manifest-xml }}'

      - name: Build vm_minimal
        uses: ./.github/actions/vm-image
        with:
          CONFIG: ${{ inputs.platform }}
          TARGET: 'vm_minimal'
          WORKSPACE: './workspace'

      - name: Build vm_multi
        uses: ./.github/actions/vm-image
        with:
          CONFIG: ${{ inputs.platform }}
          TARGET: 'vm_multi'
          WORKSPACE: './workspace'

      - name: Build sel4test
        uses: ./.github/actions/vm-image
        with:
          CONFIG: ${{ inputs.platform }}
          TARGET: 'sel4test'
          WORKSPACE: './workspace'

      - name: Build vm_qemu_virtio
        uses: ./.github/actions/vm-image
        with:
          CONFIG: ${{ inputs.platform }}
          TARGET: 'vm_qemu_virtio'
          WORKSPACE: './workspace'

      - name: Publish images to artifactory
        uses: ./.github/actions/artifact-publish
        with:
          rt-user: ${{ secrets.rt-user }}
          rt-api-key: ${{ secrets.rt-api-key }}
          rt-url: ${{ secrets.rt-url }}
          build-num: ${{ github.run_number }}
          input-paths:  |
            workspace/rpi4_vm_minimal/images/capdl-loader-image-arm-bcm2711:tii-sel4-artifacts/rpi4_vm_minimal/
            workspace/rpi4_vm_multi/images/capdl-loader-image-arm-bcm2711:tii-sel4-artifacts/rpi4_vm_multi/
            workspace/rpi4_sel4test/images/sel4test-driver-image-arm-bcm2711:tii-sel4-artifacts/rpi4_vm_sel4test/
            workspace/rpi4_vm_qemu_virtio/images/capdl-loader-image-arm-bcm2711:tii-sel4-artifacts/rpi4_vm_qemu_virtio/