---
# Copyright 2022, Technology Innovation Institute

name: Build vm images
on:
  workflow_call:
    inputs:
      manifest-url:
        description: 'Manifest repository'
        default: 'git@github.com:amalx-ssrc/tii_sel4_manifest.git'
        required: false
        type: string
      manifest-revision:
        description: 'Manifest revision'
        default: 'tii/development'
        required: false
        type: string
      manifest-file:
        description: 'Manifest file'
        default: 'default.xml'
        required: false
        type: string
      repo-override:
        description: 'Repository url with name and revision'
        default: ''
        required: false
        type: string
      branch-override:
        description: 'Name of the branch for replacing'
        type: string
        default: ''
        required: false
      platform:
        description: 'Platform config'
        default: 'rpi4_defconfig'
        required: false
        type: string

    secrets:
      ssh-key:
        description: 'ssh key for checking out source code'
        required: true
      rt-user:
        description: 'user account for artifactory'
        required: true
      rt-api-key:
        description: 'api-key for artifactory'
        required: true
      rt-url:
        description: 'artifactory url'
        required: true

jobs:
  build_images:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
      - name: Checkout code for using local actions
        uses: actions/checkout@v2
        with:
          repository: amalx-ssrc/tii_sel4_build_test
          ref: tii/dev-manifest

      - name: Display repo and branch repo-override
        run: |
          echo "repo override"
          echo ${{ inputs.repo-override }}
          echo "here branch override which is empty"
          echo ${{ inputs.branch-override }}
          echo "gihtub reponame"
          echo ${{ github.repository }}
      - name: Checkout code
        id: checkout
        uses: ./.github/actions/repo-manifest-checkout
        with:
          MANIFEST_URL: ${{ inputs.manifest-url }}
          MANIFEST_REVISION: ${{ inputs.manifest-revision }}
          MANIFEST: ${{ inputs.manifest-file }}
          SSH_KEY: ${{ secrets.ssh-key }}
          SSH_KEYSCAN_URL: 'github.com'
          WORKSPACE: './workspace'
          REPO_OVERRIDE: ${{ inputs.repo-override }}
          BRANCH_OVERRIDE: ${{ inputs.branch-override }}
      - name: Dump build info
        run: |
          echo "Using manifest:"
          echo -e '${{ steps.checkout.outputs.manifest-xml }}'

      - name: Build vm_minimal
        uses: ./.github/actions/vm-image
        with:
          CONFIG: ${{ inputs.platform }}
          TARGET: 'vm_minimal'
          WORKSPACE: './workspace'

      - name: Build vm_multi
        uses: ./.github/actions/vm-image
        with:
          CONFIG: ${{ inputs.platform }}
          TARGET: 'vm_multi'
          WORKSPACE: './workspace'

      - name: Build sel4test
        uses: ./.github/actions/vm-image
        with:
          CONFIG: ${{ inputs.platform }}
          TARGET: 'sel4test'
          WORKSPACE: './workspace'

      - name: Build vm_qemu_virtio
        uses: ./.github/actions/vm-image
        with:
          CONFIG: ${{ inputs.platform }}
          TARGET: 'vm_qemu_virtio'
          WORKSPACE: './workspace'

      - name: Publish images to artifactory
        if:  ${{ github.repository }} == 'amalx-ssrc/tii_sel4_build_test'
        uses: ./.github/actions/artifact-publish
        with:
          rt-user: ${{ secrets.rt-user }}
          rt-api-key: ${{ secrets.rt-api-key }}
          rt-url: ${{ secrets.rt-url }}
          build-num: ${{ github.run_number }}
          input-paths:  |
            workspace/rpi4_vm_minimal/images/capdl-loader-image-arm-bcm2711:tii-sel4-artifacts/rpi4_vm_minimal/
            workspace/rpi4_vm_multi/images/capdl-loader-image-arm-bcm2711:tii-sel4-artifacts/rpi4_vm_multi/
            workspace/rpi4_sel4test/images/sel4test-driver-image-arm-bcm2711:tii-sel4-artifacts/rpi4_vm_sel4test/
            workspace/rpi4_vm_qemu_virtio/images/capdl-loader-image-arm-bcm2711:tii-sel4-artifacts/rpi4_vm_qemu_virtio/
