name: Inititor2

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
jobs:
  Open-pr-verificaton:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for using local actions
        uses: actions/checkout@v3
        with:
          repository: amalx-ssrc/tii_sel4_build_test
          ref: 'tii/development-test'
          path: 'tii_sel4_build_test'

      - name: checkout manifest repo
        uses: actions/checkout@v3
        with:
          repository: 'amalx-ssrc/tii_sel4_manifest'
          ref: 'tii/development'
          path: 'tii_sel4_manifest'
      - name: manifest generation
        run: tii_sel4_build_test/scripts/open-pr.sh ${{ inputs.branch }}
      - name: Displaying
        run: cat tii_sel4_manifest/external.xml
      - name: Publish images to artifactory
        uses: amalx-ssrc/tii_sel4_build_test/.github/actions/artifact-publish@tii/development-test
        with:
          rt-user: ${{ secrets.RT_USER }}
          rt-api-key: ${{ secrets.RT_API_KEY }}
          rt-url: ${{ secrets.RT_URL}}
          input-paths:  |
            tii_sel4_manifest:tii-sel4-manifest