name: Inititor2

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      JF_ACCESS_TOKEN:
        required: true
jobs:
  Open-pr-verificaton:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for using local actions
        uses: actions/checkout@v3
        with:
          repository: amalx-ssrc/tii_sel4_build_test
          ref: 'tii/development-test'
          path: 'tii_sel4_build_test'

      - name: checkout manifest repo
        uses: actions/checkout@v3
        with:
          repository: 'amalx-ssrc/tii_sel4_manifest'
          ref: 'tii/development'
          path: 'tii_sel4_manifest-${{ inputs.branch }}'
      - name: manifest generation
        run: tii_sel4_build_test/scripts/open-pr.sh ${{ inputs.branch }}
      - name: Displaying
        run: cat tii_sel4_manifest-${{ inputs.branch }}/external.xml
      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ENV_1: ${{ secrets.JF_ACCESS_TOKEN }}
      - run: |
          jf rt u tii_sel4_manifest-${{ inputs.branch }}/ tii-sel4-manifest




      # - name: Publish images to artifactory
      #   uses: amalx-ssrc/tii_sel4_build_test/.github/actions/artifact-publish@tii/development-test
      #   with:
      #     rt-user: ${{ secrets.RT_USER }}
      #     rt-api-key: ${{ secrets.RT_API_KEY }}
      #     rt-url: ${{ secrets.RT_URL}}
      #     input-paths:  |
      #       tii_sel4_manifest:tii-sel4-manifest


      # - name: installing jf 
      #   env: 
      #       RT_USER: ${{ secrets.RT_USER }}
      #       RT_API_KEY: ${{ secrets.RT_API_KEY }}
      #       RT_URL: ${{ secrets.RT_URL }}
      #   run: |
      #     wget -qO - https://releases.jfrog.io/artifactory/jfrog-gpg-public/jfrog_public_gpg.key | sudo apt-key add -
      #     echo "deb https://releases.jfrog.io/artifactory/jfrog-debs xenial contrib" | sudo tee -a /etc/apt/sources.list
      #     sudo apt update
      #     sudo apt install -y jfrog-cli-v2-jf

      #     echo uploading artifactory
      #     jf c add --url "$RT_URL" --user "$RT_USER" --password "$RT_API_KEY" --interactive=false
      #     jf rt u tii_sel4_manifest/ tii-sel4-manifest

