name: Inititor2

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
jobs:
  Open-pr-verificaton:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for using local actions
        uses: actions/checkout@v3
        with:
          repository: amalx-ssrc/tii_sel4_build_test
          ref: 'tii/development-test'
          path: 'tii_sel4_build_test'

      - name: checkout manifest repo
        uses: actions/checkout@v3
        with:
          repository: 'amalx-ssrc/tii_sel4_manifest'
          ref: 'tii/development'
          path: 'tii_sel4_manifest'
      - name: manifest generation
        run: scripts/open-pr.sh ${{ inputs.branch }}
      - name: Displaying
        run: cat tii_sel4_manifest/external.xml