name: Repo manifest checkout workflow

on:
 workflow_call:
    inputs:
      manifest-url:
        description: 'Manifest repository'
        default: 'https://github.com/amalx-ssrc/tii_sel4_manifest'
        required: false
        type: string
      manifest-revision:
        description: 'Manifest revision'
        default: 'tii/development'
        required: false
        type: string
      manifest-file:
        description: 'Manifest file'
        default: 'default.xml'
        required: false
        type: string
      platform:
        description: 'Platform config'
        default: 'rpi4_defconfig'
        required: false
        type: string
    secrets:
      ssh-key:
        description: 'ssh key for checking out source code'
        required: true

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for using local actions
        uses: actions/checkout@v2

      - name: Checkout code
        id: checkout
        uses: ./.github/actions/repo-manifest-checkout
        with:
          MANIFEST_URL: ${{ inputs.manifest-url }}
          MANIFEST_REVISION: ${{ inputs.manifest-revision }}
          MANIFEST: ${{ inputs.manifest-file }}
          SSH_KEY: ${{ secrets.ssh-key }}
          SSH_KEYSCAN_URL: 'github.com'
          WORKSPACE: './workspace'

      - name: Upload manifest
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: workspace/



  